{"package_name": "java.util.concurrent", "subclass_list": [], "class_description": "Exception thrown by an Executor when a task cannot be\n accepted for execution. ", "class_type": "class", "typealias": [], "interface_list": [""], "class_inherit_list": ["RuntimeException"], "Methods": [{"params": [], "class_name": "RejectedExecutionException", "is_static": false, "return_value": {"return_name": "", "return_description": [], "return_type": []}, "method_name": "init", "method_description": "Constructs a RejectedExecutionException with no detail message.\n The cause is not initialized, and may subsequently be\n initialized by a call to initCause.\n", "method_declar": ""}, {"params": [{"param_name": ["message"], "param_type": "String", "param_description": " the detail message"}], "class_name": "RejectedExecutionException", "is_static": false, "return_value": {"return_name": "", "return_description": [], "return_type": []}, "method_name": "init", "method_description": "Constructs a RejectedExecutionException with the\n specified detail message. The cause is not initialized, and may\n subsequently be initialized by a call to initCause.\n", "method_declar": ""}, {"params": [{"param_name": ["message"], "param_type": "String", "param_description": " the detail message"}, {"param_name": ["cause"], "param_type": "Throwable", "param_description": " the cause (which is saved for later retrieval by the\n         Throwable.getCause() method)"}], "class_name": "RejectedExecutionException", "is_static": false, "return_value": {"return_name": "", "return_description": [], "return_type": []}, "method_name": "init", "method_description": "Constructs a RejectedExecutionException with the\n specified detail message and cause.\n", "method_declar": ""}, {"params": [{"param_name": ["cause"], "param_type": "Throwable", "param_description": " the cause (which is saved for later retrieval by the\n         Throwable.getCause() method)"}], "class_name": "RejectedExecutionException", "is_static": false, "return_value": {"return_name": "", "return_description": [], "return_type": []}, "method_name": "init", "method_description": "Constructs a RejectedExecutionException with the\n specified cause.  The detail message is set to (cause ==\n null ? null : cause.toString()) (which typically contains\n the class and detail message of cause).\n", "method_declar": ""}], "class_name": "RejectedExecutionException", "Vars": null}