{"package_name": "java.lang", "subclass_list": [], "class_description": "Thrown when an exceptional arithmetic condition has occurred. For\n example, an integer \"divide by zero\" throws an\n instance of this class.\n\n ArithmeticException objects may be constructed by the\n virtual machine as if Throwable#Throwable(String,\n Throwable, boolean, boolean). ", "class_type": "class", "typealias": [], "interface_list": [""], "class_inherit_list": ["RuntimeException"], "Methods": [{"params": [], "class_name": "ArithmeticException", "is_static": false, "return_value": {"return_name": "", "return_description": [], "return_type": []}, "method_name": "init", "method_description": "Constructs an ArithmeticException with no detail\n message.\n", "method_declar": ""}, {"params": [{"param_name": ["s"], "param_type": "String", "param_description": " the detail message."}], "class_name": "ArithmeticException", "is_static": false, "return_value": {"return_name": "", "return_description": [], "return_type": []}, "method_name": "init", "method_description": "Constructs an ArithmeticException with the specified\n detail message.\n", "method_declar": ""}], "class_name": "ArithmeticException", "Vars": null}